name: publish dev
on:
  push:
    branches:
      - 'dev'
    paths:
      - 'src/main/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CHANGELOG: ${{ github.event.head_commit.message }}
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        ref: dev
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: setup jdk 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'microsoft'
    - name: publish alpha to modrinth
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: modrinth
