name: publish dev
on:
  push:
    branches:
      - 'dev'
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: setup jdk 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'microsoft'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: publish to modrinth (dev)
      run: ./gradlew modrinth
